2020-04-16 18:44:24.012 [error] <0.918.0> gen_server <0.918.0> terminated with reason: {socket_error,timeout}
2020-04-16 18:44:24.013 [error] <0.918.0> CRASH REPORT Process <0.918.0> with 0 neighbours exited with reason: {socket_error,timeout} in gen_server:handle_common_reply/8 line 751
2020-04-16 18:44:24.013 [error] <0.900.0> gen_server <0.900.0> terminated with reason: {socket_error,timeout}
2020-04-16 18:44:24.013 [error] <0.900.0> CRASH REPORT Process <0.900.0> with 0 neighbours exited with reason: {socket_error,timeout} in gen_server:handle_common_reply/8 line 751
2020-04-16 18:44:24.013 [error] <0.879.0> gen_server <0.879.0> terminated with reason: {socket_error,timeout}
2020-04-16 18:44:24.013 [error] <0.879.0> CRASH REPORT Process <0.879.0> with 0 neighbours exited with reason: {socket_error,timeout} in gen_server:handle_common_reply/8 line 751
2020-04-16 18:44:24.013 [error] <0.914.0> gen_server <0.914.0> terminated with reason: {socket_error,timeout}
2020-04-16 18:44:24.013 [error] <0.913.0> Supervisor {<0.913.0>,amqp_connection_type_sup} had child main_reader started with amqp_main_reader:start_link(#Port<0.1239>, <0.914.0>, <0.916.0>, {method,rabbit_framing_amqp_0_9_1}, <<"client 192.168.1.5:60374 -> 13.230.225.193:5672">>) at <0.918.0> exit with reason {socket_error,timeout} in context child_terminated
2020-04-16 18:44:24.013 [error] <0.874.0> Supervisor {<0.874.0>,amqp_connection_type_sup} had child main_reader started with amqp_main_reader:start_link(#Port<0.1236>, <0.875.0>, <0.877.0>, {method,rabbit_framing_amqp_0_9_1}, <<"client 192.168.1.5:60317 -> 13.230.225.193:5672">>) at <0.879.0> exit with reason {socket_error,timeout} in context child_terminated
2020-04-16 18:44:24.014 [error] <0.913.0> Supervisor {<0.913.0>,amqp_connection_type_sup} had child main_reader started with amqp_main_reader:start_link(#Port<0.1239>, <0.914.0>, <0.916.0>, {method,rabbit_framing_amqp_0_9_1}, <<"client 192.168.1.5:60374 -> 13.230.225.193:5672">>) at <0.918.0> exit with reason reached_max_restart_intensity in context shutdown
2020-04-16 18:44:24.014 [error] <0.874.0> Supervisor {<0.874.0>,amqp_connection_type_sup} had child main_reader started with amqp_main_reader:start_link(#Port<0.1236>, <0.875.0>, <0.877.0>, {method,rabbit_framing_amqp_0_9_1}, <<"client 192.168.1.5:60317 -> 13.230.225.193:5672">>) at <0.879.0> exit with reason reached_max_restart_intensity in context shutdown
2020-04-16 18:44:24.014 [error] <0.896.0> gen_server <0.896.0> terminated with reason: {socket_error,timeout}
2020-04-16 18:44:24.014 [error] <0.895.0> Supervisor {<0.895.0>,amqp_connection_type_sup} had child main_reader started with amqp_main_reader:start_link(#Port<0.1238>, <0.896.0>, <0.898.0>, {method,rabbit_framing_amqp_0_9_1}, <<"client 192.168.1.5:60360 -> 13.230.225.193:5672">>) at <0.900.0> exit with reason {socket_error,timeout} in context child_terminated
2020-04-16 18:44:24.014 [error] <0.895.0> Supervisor {<0.895.0>,amqp_connection_type_sup} had child main_reader started with amqp_main_reader:start_link(#Port<0.1238>, <0.896.0>, <0.898.0>, {method,rabbit_framing_amqp_0_9_1}, <<"client 192.168.1.5:60360 -> 13.230.225.193:5672">>) at <0.900.0> exit with reason reached_max_restart_intensity in context shutdown
2020-04-16 18:44:24.014 [error] <0.875.0> gen_server <0.875.0> terminated with reason: {socket_error,timeout}
2020-04-16 18:44:24.015 [error] <0.896.0> CRASH REPORT Process <0.896.0> with 0 neighbours exited with reason: {socket_error,timeout} in gen_server:handle_common_reply/8 line 751
2020-04-16 18:44:24.015 [error] <0.894.0> Supervisor {<0.894.0>,amqp_connection_sup} had child connection started with amqp_gen_connection:start_link(<0.895.0>, {amqp_params_network,<<"rabbitmq_dev">>,<<"bUhUhDnfb3+xe3XPgliW+cjcCAaC0z7f05Jvngkc+5kHIPfKyXMNsGB...">>,...}) at <0.896.0> exit with reason {socket_error,timeout} in context child_terminated
2020-04-16 18:44:24.015 [error] <0.894.0> Supervisor {<0.894.0>,amqp_connection_sup} had child connection started with amqp_gen_connection:start_link(<0.895.0>, {amqp_params_network,<<"rabbitmq_dev">>,<<"bUhUhDnfb3+xe3XPgliW+cjcCAaC0z7f05Jvngkc+5kHIPfKyXMNsGB...">>,...}) at <0.896.0> exit with reason reached_max_restart_intensity in context shutdown
2020-04-16 18:44:24.015 [error] <0.914.0> CRASH REPORT Process <0.914.0> with 0 neighbours exited with reason: {socket_error,timeout} in gen_server:handle_common_reply/8 line 751
2020-04-16 18:44:24.015 [error] <0.875.0> CRASH REPORT Process <0.875.0> with 0 neighbours exited with reason: {socket_error,timeout} in gen_server:handle_common_reply/8 line 751
2020-04-16 18:44:24.016 [error] <0.912.0> Supervisor {<0.912.0>,amqp_connection_sup} had child connection started with amqp_gen_connection:start_link(<0.913.0>, {amqp_params_network,<<"rabbitmq_dev">>,<<"y9Z0WJOMRFrSvMBYt1NtU1k99jStxyTOR/uvjmiNsJ9OlYSUM1nMR8d...">>,...}) at <0.914.0> exit with reason {socket_error,timeout} in context child_terminated
2020-04-16 18:44:24.016 [error] <0.912.0> Supervisor {<0.912.0>,amqp_connection_sup} had child connection started with amqp_gen_connection:start_link(<0.913.0>, {amqp_params_network,<<"rabbitmq_dev">>,<<"y9Z0WJOMRFrSvMBYt1NtU1k99jStxyTOR/uvjmiNsJ9OlYSUM1nMR8d...">>,...}) at <0.914.0> exit with reason reached_max_restart_intensity in context shutdown
2020-04-16 18:44:24.016 [error] <0.873.0> Supervisor {<0.873.0>,amqp_connection_sup} had child connection started with amqp_gen_connection:start_link(<0.874.0>, {amqp_params_network,<<"rabbitmq_dev">>,<<"Es+7WE1YXSGb7L97MGVWVlRntrhM0mxUeVxxFndzl0KROkr71TmpoT0...">>,...}) at <0.875.0> exit with reason {socket_error,timeout} in context child_terminated
2020-04-16 18:44:24.016 [error] <0.873.0> Supervisor {<0.873.0>,amqp_connection_sup} had child connection started with amqp_gen_connection:start_link(<0.874.0>, {amqp_params_network,<<"rabbitmq_dev">>,<<"Es+7WE1YXSGb7L97MGVWVlRntrhM0mxUeVxxFndzl0KROkr71TmpoT0...">>,...}) at <0.875.0> exit with reason reached_max_restart_intensity in context shutdown
2020-04-16 18:44:24.016 [error] <0.873.0> Supervisor {<0.873.0>,amqp_connection_sup} had child connection_type_sup started with amqp_connection_type_sup:start_link() at <0.874.0> exit with reason shutdown in context shutdown_error
2020-04-16 18:54:15.236 [error] <0.532.0> gen_server <0.532.0> terminated with reason: heartbeat_timeout
2020-04-16 18:54:15.237 [error] <0.532.0> CRASH REPORT Process <0.532.0> with 0 neighbours exited with reason: heartbeat_timeout in gen_server:handle_common_reply/8 line 751
2020-04-16 18:54:15.237 [error] <0.530.0> Supervisor {<0.530.0>,amqp_connection_sup} had child connection started with amqp_gen_connection:start_link(<0.531.0>, {amqp_params_network,<<"rabbitmq_dev">>,<<"vuX7q+MOrZk1Qa07J6np/OcTF93OSFKQtLGLtm6WZUaFfa1xZKNLkKu...">>,...}) at <0.532.0> exit with reason heartbeat_timeout in context child_terminated
2020-04-16 18:54:15.237 [error] <0.530.0> Supervisor {<0.530.0>,amqp_connection_sup} had child connection started with amqp_gen_connection:start_link(<0.531.0>, {amqp_params_network,<<"rabbitmq_dev">>,<<"vuX7q+MOrZk1Qa07J6np/OcTF93OSFKQtLGLtm6WZUaFfa1xZKNLkKu...">>,...}) at <0.532.0> exit with reason reached_max_restart_intensity in context shutdown
2020-04-16 19:05:13.598 [error] <0.426.0> gen_server <0.426.0> terminated with reason: heartbeat_timeout
2020-04-16 19:05:13.599 [error] <0.426.0> CRASH REPORT Process <0.426.0> with 0 neighbours exited with reason: heartbeat_timeout in gen_server:handle_common_reply/8 line 751
2020-04-16 19:05:13.599 [error] <0.424.0> Supervisor {<0.424.0>,amqp_connection_sup} had child connection started with amqp_gen_connection:start_link(<0.425.0>, {amqp_params_network,<<"rabbitmq_dev">>,<<"Lf5gkCgBoG21s8DJzR6bEhkZGKKCROHzj/kv0AufaeVSvGEzMN/ZJQd...">>,...}) at <0.426.0> exit with reason heartbeat_timeout in context child_terminated
2020-04-16 19:05:13.600 [error] <0.424.0> Supervisor {<0.424.0>,amqp_connection_sup} had child connection started with amqp_gen_connection:start_link(<0.425.0>, {amqp_params_network,<<"rabbitmq_dev">>,<<"Lf5gkCgBoG21s8DJzR6bEhkZGKKCROHzj/kv0AufaeVSvGEzMN/ZJQd...">>,...}) at <0.426.0> exit with reason reached_max_restart_intensity in context shutdown
2020-04-16 19:05:19.376 [error] <0.437.0> gen_server <0.437.0> terminated with reason: heartbeat_timeout
2020-04-16 19:05:19.378 [error] <0.437.0> CRASH REPORT Process <0.437.0> with 0 neighbours exited with reason: heartbeat_timeout in gen_server:handle_common_reply/8 line 751
2020-04-16 19:05:19.378 [error] <0.435.0> Supervisor {<0.435.0>,amqp_connection_sup} had child connection started with amqp_gen_connection:start_link(<0.436.0>, {amqp_params_network,<<"rabbitmq_dev">>,<<"y4g0DVj2nlJYZE63LoDf0354cUndmuZp91EwVF0Hlc3oWa4I01+ZGBh...">>,...}) at <0.437.0> exit with reason heartbeat_timeout in context child_terminated
2020-04-16 19:05:19.379 [error] <0.435.0> Supervisor {<0.435.0>,amqp_connection_sup} had child connection started with amqp_gen_connection:start_link(<0.436.0>, {amqp_params_network,<<"rabbitmq_dev">>,<<"y4g0DVj2nlJYZE63LoDf0354cUndmuZp91EwVF0Hlc3oWa4I01+ZGBh...">>,...}) at <0.437.0> exit with reason reached_max_restart_intensity in context shutdown
